### PR TITLE
Fix EditDonation duplicate date check

### LINKED ISSUE #141: Editing donation record to same date as existing record not properly handled
When the user edits a donor’s donation record, cases where the new donation date is one day before or after an existing record are properly handled with the correct error message.

However, if the user edits the record to the exact same date as another donation record for the same person, the app displays an unintuitive error message to the user: 

"An error has occured under the hood! 
Your previous command was likely not properly captured. Please try again."

### PR DESCRIPTION
**Pull request by flyingcat9**
Fixes #141, great catch.

Still adding test cases.

### CODE REVIEW

File: src/main/java/bloodnet/logic/commands/EditDonationCommand.java [hunk 1]
```diff
@@ -83,8 +78,8 @@ public InputResponse execute(Model model) throws CommandException {
             throw new CommandException(concatenatedMessage);
         }
 
-        if (recordToEdit.equals(editedDonationRecord)) {
-            throw new CommandException(MESSAGE_DUPLICATE_DONATION_RECORD);
+        if (!recordToEdit.isSameDonationRecord(editedDonationRecord) && model.hasDonationRecord(editedDonationRecord)) {
+            throw new CommandException(MESSAGE_DONATION_RECORD_ALREADY_EXISTS);
```
Comment (fsythw) [inline src/main/java/bloodnet/logic/commands/EditDonationCommand.java]: Nicely done
