### PR TITLE
Fix hyperlinking and message for date of birth

### LINKED ISSUE #129: Broken hyperlinks in the UG command table
Image

Currently, the linking for the command table is not working and it currently only works for the command add. For the rest of the commands, it leads to a link that seems to be nonexistent unfortunately. 

To fix, the links will be rechecked and altered so that users are able to quickly reference any command or guideline.

### LINKED ISSUE #134: Add validation for quantity of blood when creating/editing donation record
Non-critical bug.

Currently we can specify any positive quantity for the blood volume (eg. 100000 ml of blood donated in a single session is not rejected). Perhaps we should have an upper limit on blood volume donatable in a session (may have to consult online sources to find max allowable blood donation in a single session).

### LINKED ISSUE #165: Date of birth message can be more specific as to the exact date of 130 years ago.

### PR DESCRIPTION
**Pull request by flyingcat9**
Fixes #129 with the hyperlinking and fixes #134 in terms of quantity of blood type. 

Also fixes #165 by making the message more consistent with the donation date messages.

### CODE REVIEW

File: src/test/java/bloodnet/model/donationrecord/BloodVolumeTest.java [hunk 1]
```diff
@@ -32,10 +32,12 @@ public void isValidBloodVolume() {
         assertFalse(BloodVolume.isValidBloodVolume("400.0")); // not integer
         assertFalse(BloodVolume.isValidBloodVolume("qddewr2")); // letters
         assertFalse(BloodVolume.isValidBloodVolume("-1")); // negative number
+        assertFalse(BloodVolume.isValidBloodVolume("500")); // invalid according to HSA guidelines
```
Comment (fsythw) [inline src/test/java/bloodnet/model/donationrecord/BloodVolumeTest.java]: Nice that you edited the test cases too

**Review by fsythw — APPROVED** [review]
LGTM!
