### PR TITLE
Beautify help box

### LINKED ISSUE #106: Replace all references to "displayed person list" in messages to "donor list" for consistency with the UI and user guide
In some usage messages, the donor list is referred to as the "person list", which can cause confusion.

### LINKED ISSUE #124: Update help message

### LINKED ISSUE #133: Ensure consistency in the help messages
In terms of scrolling and readability so that it is easier for readers. Also, ensuring that the examples/phrases are consistent with what is in the UG.

### LINKED ISSUE #142: Inconsistency when running find then another command
Similar to #143, if you were to run find, then run editdonation then it causes the system to produce the message that there is an error under the hood. 

Cause: If you are to filter the model, it would affect the filtered donor list. However, the donation record list is not filtered. Therefore, this leads to the donor list not linking to a donor record.  In the editdonation class, you rely on the filtered person list to check for the person it is related to, but it would crash if it was filtered.

### LINKED ISSUE #143: Error when running findeligible and then another command
Similar to #142, when running findeligible and then another command such as editdonation, the same error "An error has occured under the hood! 
Your previous command was likely not properly captured. Please try again." appears which is not really good for debugging for the user."

Image

Cause: Same as #142. Checking for a null person seems to fix the issue.

### LINKED ISSUE #146: Index not very specific for some help messages
Some help messages do not explicitly specify whether it's for the donor record or the donation record which might make users confused.

### LINKED ISSUE #156: Findeligible usage message fails to mention about the 12-week-since-last-donation rule.
Findeligible usage message fails to mention about the 12-week-since-last-donation rule. Currently, it says: “findeligible: Finds all people who are eligible to donate blood for the specified blood type(s) (case-insensitive) 
and displays them as a list with index numbers. 
All eligible blood donors must be at least 16 (inclusive) years old.
The maximum age for first-time donors is generally 60 years and 354 days, but repeat donors may have different age limits 
depending on donation history. 
Parameters: BLOOD_TYPE(S) 
Example: findeligible O+ A+ B+”
**How to reproduce:** Run "findeligible"
**Problem:** Users who are not aware of this requirement may expect certain donors to show up, and when they don’t, may be very confused and think it is a bug with the system.

### PR DESCRIPTION
**Pull request by flyingcat9**
Fixes #124 and fixes #106 which in essence, is improving upon the current help message.  It also fixes #133 by implementing setWrapText for the help box.

Changes
1. Added a class to store each instruction usage.
2. Added a class that stores all of the message usages for each command.
3. Altered colour scheme of the help box to fit with PR #122. 

image

Additionally, it fixes #156 by adding the 12 week requirement in the message usage. 

It also fixes #146 by ensuring that all indexes are consistent and clearly display whether the index is for the donation record or the donor.

Furthermore it fixes #142 and fixes #143 by throwing an error if the filtered person is not in the list.

### CODE REVIEW

File: src/main/java/bloodnet/logic/commands/AddDonationCommand.java [hunk 1]
```diff
@@ -26,16 +26,16 @@ public class AddDonationCommand extends Command {
...
-            + "the person identified by their index number in the displayed person list.\n"
-            + "Parameters: "
-            + PREFIX_PERSON_INDEX_ONE_BASED + "PERSON INDEX (must be positive integer) "
-            + PREFIX_DONATION_DATE + "DONATION DATE (DD-MM-YYYY) "
-            + PREFIX_BLOOD_VOLUME + "BLOOD VOLUME (IN MILLILITRES)\n"
-            + "Example: " + COMMAND_WORD + " "
+    public static final CommandInformation COMMAND_INFORMATION = new CommandInformation(COMMAND_WORD,
+            "Adds a donation "
+            + "record for the donor identified by their index number in the displayed donor list.",
+            "Parameters: " + PREFIX_PERSON_INDEX_ONE_BASED + "PERSON INDEX (must be positive integer) "
```
[the remark this answers is not in the document]
Comment (flyingcat9) [reply src/main/java/bloodnet/logic/commands/AddDonationCommand.java]: Thanks!

File: src/main/java/bloodnet/ui/HelpWindow.java [hunk 2]
```diff
@@ -34,7 +39,14 @@ public class HelpWindow extends UiPart<Stage> {
      */
     public HelpWindow(Stage root) {
         super(FXML, root);
-        helpMessage.setText(HELP_MESSAGE);
+        Rectangle2D screenBounds = Screen.getPrimary().getVisualBounds();
+        getRoot().setWidth(screenBounds.getWidth() * 0.6);
+        getRoot().setHeight(screenBounds.getHeight() * 0.8);
```
Comment (fsythw) [inline src/main/java/bloodnet/ui/HelpWindow.java]: Can consider adding `root.setResizable(true);`

Comment (flyingcat9) [reply src/main/java/bloodnet/ui/HelpWindow.java]: Added, thanks for the help!

File: src/main/java/bloodnet/logic/commands/ClearCommand.java [hunk 3]
```diff
@@ -9,13 +9,16 @@
 import bloodnet.model.Model;
 
 /**
- * Clears the bloodnet.
+ * Clears the BloodNet donor list.
```
[the remark this answers is not in the document]
Comment (flyingcat9) [reply src/main/java/bloodnet/logic/commands/ClearCommand.java]: Good catch!

File: src/main/java/bloodnet/logic/commands/EditDonationCommand.java [hunk 4]
```diff
@@ -116,15 +119,15 @@ private DonationRecord getDonationRecordToEdit(Model model) throws CommandExcept
      */
     private Person getPersonToEditRecordFor(Model model, DonationRecord donationRecord) throws CommandException {
         requireNonNull(model);
+        requireNonNull(donationRecord);
         List<Person> personList = model.getFilteredPersonList();
```
Comment (adityagk753) [inline src/main/java/bloodnet/logic/commands/EditDonationCommand.java]: Correct me if I'm wrong, but I believe the correct way to fix issue #142 is to change line 123 to `List<Person> personList = model.getBloodNet().getPersonList()`. This is so that this `EditDonationCommand` will try to find the Person object corresponding to `donationRecord.getPersonId()` in the FULL person list, instead of in the filtered person list.

Throwing a `CommandException` does not fix the problem. If a person corresponding to the donation record the user is trying to edit is not found, indeed a `CommandException` is thrown here, instead of a `NullPointerException` being thrown by the calling method (that is, .execute()).

Although the error is indeed displayed to the user nicely now, it does not fix the underlying issue that the user should be able to edit the donation record, even if the person is not shown in the donor list.

Comment (Eugene-Lek) [reply src/main/java/bloodnet/logic/commands/EditDonationCommand.java]: I agree. I was gonna mention this too HAHA

Comment (flyingcat9) [reply src/main/java/bloodnet/logic/commands/EditDonationCommand.java]: Great catch! I did that to be more consistent with deletedonation, but I can definitely edit this.

I guess the original idea was that findeligible would only be linked to the donation records from the filtered persons.

Comment (flyingcat9) [reply src/main/java/bloodnet/logic/commands/EditDonationCommand.java]: How about for adddonation or finddonations? If you were to filter, then how would you know which person it is for? 

Can mention in the enhancements though.

**Review by adityagk753 — CHANGES_REQUESTED** [review]
Have listed a few suggestions below. Other than that LGTM, can merge.

1. In the help box, list and clear commands instructions should be together with the donor commands (perhaps put them directly below find command instructions)
3. Might want to include the caveat for delete (up to you though, just a suggestion): only allowed if there is no donation record for that person
4. Might want to change the message slightly for findeligible to be more precise:

> Finds all donors who are eligible to donate blood for the specified blood type(s) (case-insensitive) and displays them as a list with index numbers.
> 
> All eligible donors must be at least 16 years old on the donation date.
> For first-time donors, the donation date must be strictly before their 61st birthday.
> For returning donors, they must have made a previous donation within the last 3 years from the donation date (inclusive of that donation date), and the donation date must be strictly before their 66th birthday.
> In addition, there must be a minimum of 84 days between any two consecutive donations.
