### PR TITLE
Edit variable names and fix check for optionalPerson

### LINKED ISSUE #112: Fix variable names in EditDonationCommand

### PR DESCRIPTION
**Pull request by adityagk753**
Fixes #112 

1. Fix variable names to be consistent with EditCommand
2. Fix potential bug (optionalPerson will not be null, use optionalPerson.isPresent() instead)
3. Fix some javadoc inconsistencies

### CODE REVIEW

File: src/main/java/bloodnet/logic/commands/EditDonationCommand.java [hunk 1]
```diff
@@ -45,26 +45,26 @@ public class EditDonationCommand extends Command {
     private final EditDonationRecordDescriptor editDonationRecordDescriptor;
 
     /**
-     * @param index                of the person in the filtered person list to edit
-     * @param editPersonDescriptor details to edit the person with
+     * @param index of the person in the filtered person list to edit
```
Comment (flyingcat9) [inline src/main/java/bloodnet/logic/commands/EditDonationCommand.java]: So sorry, but you could also change person list to blood donation record list?
